# SPDX-License-Identifier: MIT
# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ast2600-lab"
BBFILE_PATTERN_ast2600-lab := "^${LAYERDIR}/"
BBFILE_PRIORITY_ast2600-lab = "6"
LAYERVERSION_ast2600-lab = "1"

LAYERDEPENDS_ast2600-lab = "phosphor-layer"
LAYERSERIES_COMPAT_ast2600-lab = "wrynose whinlatter"
